# Generated by Django 2.2.10 on 2021-08-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='self_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
