# Generated by Django 2.2.10 on 2021-08-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_auto_20210830_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='many_choice',
        ),
        migrations.AddField(
            model_name='answer',
            name='multiple_choice',
            field=models.ManyToManyField(blank=True, to='api_v1.Choice'),
        ),
    ]
